// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: user.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddReq) Reset() {
	*x = UserAddReq{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddReq) ProtoMessage() {}

func (x *UserAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddReq.ProtoReflect.Descriptor instead.
func (*UserAddReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserAddReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type UserAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddResp) Reset() {
	*x = UserAddResp{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddResp) ProtoMessage() {}

func (x *UserAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddResp.ProtoReflect.Descriptor instead.
func (*UserAddResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserAddResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *UserAddResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type RoleAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int32                  `protobuf:"varint,1,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAddReq) Reset() {
	*x = RoleAddReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAddReq) ProtoMessage() {}

func (x *RoleAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAddReq.ProtoReflect.Descriptor instead.
func (*RoleAddReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *RoleAddReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RoleAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RoleAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAddResp) Reset() {
	*x = RoleAddResp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAddResp) ProtoMessage() {}

func (x *RoleAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAddResp.ProtoReflect.Descriptor instead.
func (*RoleAddResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *RoleAddResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RoleAddResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type QuanXianAddReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           int32                  `protobuf:"varint,1,opt,name=Rid,proto3" json:"Rid,omitempty"`
	Uid           int32                  `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuanXianAddReq) Reset() {
	*x = QuanXianAddReq{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuanXianAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuanXianAddReq) ProtoMessage() {}

func (x *QuanXianAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuanXianAddReq.ProtoReflect.Descriptor instead.
func (*QuanXianAddReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *QuanXianAddReq) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *QuanXianAddReq) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *QuanXianAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type QuanXianAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuanXianAddResp) Reset() {
	*x = QuanXianAddResp{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuanXianAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuanXianAddResp) ProtoMessage() {}

func (x *QuanXianAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuanXianAddResp.ProtoReflect.Descriptor instead.
func (*QuanXianAddResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *QuanXianAddResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *QuanXianAddResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type RoleListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	List          []*RoleList            `protobuf:"bytes,2,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListReq) Reset() {
	*x = RoleListReq{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListReq) ProtoMessage() {}

func (x *RoleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListReq.ProtoReflect.Descriptor instead.
func (*RoleListReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *RoleListReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoleListReq) GetList() []*RoleList {
	if x != nil {
		return x.List
	}
	return nil
}

type RoleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           int32                  `protobuf:"varint,1,opt,name=Rid,proto3" json:"Rid,omitempty"`
	Uid           int32                  `protobuf:"varint,2,opt,name=Uid,proto3" json:"Uid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleList) Reset() {
	*x = RoleList{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleList) ProtoMessage() {}

func (x *RoleList) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleList.ProtoReflect.Descriptor instead.
func (*RoleList) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *RoleList) GetRid() int32 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *RoleList) GetUid() int32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RoleList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RoleListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	List          string                 `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleListResp) Reset() {
	*x = RoleListResp{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleListResp) ProtoMessage() {}

func (x *RoleListResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleListResp.ProtoReflect.Descriptor instead.
func (*RoleListResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *RoleListResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RoleListResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RoleListResp) GetList() string {
	if x != nil {
		return x.List
	}
	return ""
}

type RoleDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleDeleteReq) Reset() {
	*x = RoleDeleteReq{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeleteReq) ProtoMessage() {}

func (x *RoleDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeleteReq.ProtoReflect.Descriptor instead.
func (*RoleDeleteReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *RoleDeleteReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RoleDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleDeleteResp) Reset() {
	*x = RoleDeleteResp{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleDeleteResp) ProtoMessage() {}

func (x *RoleDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleDeleteResp.ProtoReflect.Descriptor instead.
func (*RoleDeleteResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *RoleDeleteResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RoleDeleteResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x05proto\"<\n" +
	"\n" +
	"UserAddReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"3\n" +
	"\vUserAddResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"2\n" +
	"\n" +
	"RoleAddReq\x12\x10\n" +
	"\x03Uid\x18\x01 \x01(\x05R\x03Uid\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"3\n" +
	"\vRoleAddResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"H\n" +
	"\x0eQuanXianAddReq\x12\x10\n" +
	"\x03Rid\x18\x01 \x01(\x05R\x03Rid\x12\x10\n" +
	"\x03Uid\x18\x02 \x01(\x05R\x03Uid\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\"7\n" +
	"\x0fQuanXianAddResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"B\n" +
	"\vRoleListReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12#\n" +
	"\x04List\x18\x02 \x03(\v2\x0f.proto.RoleListR\x04List\"B\n" +
	"\bRoleList\x12\x10\n" +
	"\x03Rid\x18\x01 \x01(\x05R\x03Rid\x12\x10\n" +
	"\x03Uid\x18\x02 \x01(\x05R\x03Uid\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\"H\n" +
	"\fRoleListResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x12\n" +
	"\x04list\x18\x03 \x01(\tR\x04list\"\x1f\n" +
	"\rRoleDeleteReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"6\n" +
	"\x0eRoleDeleteResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2\xa1\x02\n" +
	"\rStreamGreeter\x120\n" +
	"\aUserAdd\x12\x11.proto.UserAddReq\x1a\x12.proto.UserAddResp\x120\n" +
	"\aRoleAdd\x12\x11.proto.RoleAddReq\x1a\x12.proto.RoleAddResp\x123\n" +
	"\bRoleList\x12\x12.proto.RoleListReq\x1a\x13.proto.RoleListResp\x129\n" +
	"\n" +
	"RoleDelete\x12\x14.proto.RoleDeleteReq\x1a\x15.proto.RoleDeleteResp\x12<\n" +
	"\vQuanXianAdd\x12\x15.proto.QuanXianAddReq\x1a\x16.proto.QuanXianAddRespB\x04Z\x02./b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_proto_goTypes = []any{
	(*UserAddReq)(nil),      // 0: proto.UserAddReq
	(*UserAddResp)(nil),     // 1: proto.UserAddResp
	(*RoleAddReq)(nil),      // 2: proto.RoleAddReq
	(*RoleAddResp)(nil),     // 3: proto.RoleAddResp
	(*QuanXianAddReq)(nil),  // 4: proto.QuanXianAddReq
	(*QuanXianAddResp)(nil), // 5: proto.QuanXianAddResp
	(*RoleListReq)(nil),     // 6: proto.RoleListReq
	(*RoleList)(nil),        // 7: proto.RoleList
	(*RoleListResp)(nil),    // 8: proto.RoleListResp
	(*RoleDeleteReq)(nil),   // 9: proto.RoleDeleteReq
	(*RoleDeleteResp)(nil),  // 10: proto.RoleDeleteResp
}
var file_user_proto_depIdxs = []int32{
	7,  // 0: proto.RoleListReq.List:type_name -> proto.RoleList
	0,  // 1: proto.StreamGreeter.UserAdd:input_type -> proto.UserAddReq
	2,  // 2: proto.StreamGreeter.RoleAdd:input_type -> proto.RoleAddReq
	6,  // 3: proto.StreamGreeter.RoleList:input_type -> proto.RoleListReq
	9,  // 4: proto.StreamGreeter.RoleDelete:input_type -> proto.RoleDeleteReq
	4,  // 5: proto.StreamGreeter.QuanXianAdd:input_type -> proto.QuanXianAddReq
	1,  // 6: proto.StreamGreeter.UserAdd:output_type -> proto.UserAddResp
	3,  // 7: proto.StreamGreeter.RoleAdd:output_type -> proto.RoleAddResp
	8,  // 8: proto.StreamGreeter.RoleList:output_type -> proto.RoleListResp
	10, // 9: proto.StreamGreeter.RoleDelete:output_type -> proto.RoleDeleteResp
	5,  // 10: proto.StreamGreeter.QuanXianAdd:output_type -> proto.QuanXianAddResp
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
